name: Build and Package App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build with PyInstaller
        run: |
          # This builds the folder-based app
          pyinstaller --noconsole --name="QuickDraw" src/mainUI.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QuickDraw-${{ matrix.os }}
          path: dist/
